[build-system]
requires = ["setuptools>=64.0"]
build-backend = "setuptools.build_meta"

[project]
name = "chat_agent"
version = "0.1.0"
description = "A chatbot agent package"
dependencies = [
    "requests",
    "pydantic",
    "pydantic-core",
    "fastapi",
    "google-genai",
    "python-dotenv",
    "google-cloud-firestore",
    "google-cloud-core",
    "google-cloud-discoveryengine",
    "google-cloud-documentai",
    "firebase-admin",
    "langchain",
    "langchain-google-vertexai",
    "langchain-google-community",
    "uvicorn",
    "psutil",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["chat_agent*"]
