
import os
import dotenv
from chat_agent.tools import ToolList

dotenv.load_dotenv()

def test_pdf_generation():
    print("Testing PDF generation tool...")
    tools = ToolList()
    
    # Simulate tool call
    title = "Test Sustainability Report"
    content = "This is a test report generated by the Gemini agent.\n\nKey Findings:\n- Energy consumption is down 10%.\n- CO2 emissions reduced by 5 tons.\n- Sustainability strategy is on track."
    user_id = "test_user_antigravity"
    
    result = tools._generate_pdf_report(title, content, user_id)
    print(result)

if __name__ == "__main__":
    test_pdf_generation()
